name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "bunx prisma generate"
dev = "bunx prisma migrate deploy && bunx react-router dev"
